// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJf3AIEHLwIsAbMxBftBgZaKj2_k7bIWo',
    appId: '1:514424549515:web:68d88d59b75fb11b41a48e',
    messagingSenderId: '514424549515',
    projectId: 'brew-crew-40bf0',
    authDomain: 'brew-crew-40bf0.firebaseapp.com',
    storageBucket: 'brew-crew-40bf0.appspot.com',
    measurementId: 'G-R80BJCY39F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDOFYzjWKgdN9OGfH45nyUt7cTCSzGMQ8',
    appId: '1:514424549515:android:4858175d5255fbd341a48e',
    messagingSenderId: '514424549515',
    projectId: 'brew-crew-40bf0',
    storageBucket: 'brew-crew-40bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCED2Ic9J2JQ9QMIixGRJa4KTiAEWoixwk',
    appId: '1:514424549515:ios:ae45dab85edf557b41a48e',
    messagingSenderId: '514424549515',
    projectId: 'brew-crew-40bf0',
    storageBucket: 'brew-crew-40bf0.appspot.com',
    iosClientId: '514424549515-ma1ffopnq7nlo5l225e28ikme76fsnhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTextEditorWeb',
  );
}
